# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Janus Analytica
email: 
description: The Jekyll version of the Hyperspace theme by HTML5 UP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://janus-analytica.github.io" # the base hostname & protocol for your site

# Social settings
500px_url: 
facebook_url: 
github_url: https://github.com/janus-analytica 
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/janusanalytica

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: janusanalytica
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
